const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"垃圾信息",
                        "menuJump":"列表",
                        "tableName":"lajixinxi"
                    }
                ],
                "menu":"垃圾信息"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"我的留言信息",
                        "menuJump":"列表",
                        "tableName":"lajixinxiLiuyan"
                    }
                ],
                "menu":"我的留言信息"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"新闻信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻信息"
            }
			,
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"试卷列表",
                        "tableName":"exampaper"
                    },
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"评测记录",
                        "tableName":"examrecord"
                    }
                ],
                "menu":"评测管理"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
